### PR TITLE
Adds keeping the order of elements

### LINKED ISSUE #52: Is there a way to force order of elements in the built XML?
It would be great to be able to order the elements exactly like they are ordered in the class definition. It would help compare input to output if they were in the same order.

### PR DESCRIPTION
**Pull request by deiga**
- fixes #52 by adding an array to keep track of order
- Adds configuration for TravsiCI
- Fixes development compatibility with 1.8.7

### CODE REVIEW

**Comment by Danicela** [comment]
I search to make elements ordering.
Why isn't this update also available in nokogiri-happymapper ?
Am I obliged to use nokogiri-happymapper-deiga to get elements ordering ? (or is there any other way, even if more complicated?)
What are the other differences between nokogiri-happymapper and nokogiri-happymapper-deiga ? (is the first abandonned?)

**Comment by deiga** [comment]
My Pull Request was never accepted, I think `nokogiri-happymapper` has been abandoned.

Ordering was the only thing I added, here's the [changelog](https://github.com/deiga/happymapper/blob/master/CHANGELOG.md)

I didn't find any other way, when I was working at the problem.

**Comment by Danicela** [comment]
[quote]Added compatibility with Ruby 1.8.7
Added ordering of elements[/quote]

What has been modified for Ruby 1.8.7 ? That's the version I use but dam5s's happymapper already works on 1.8.7 ?

**Comment by deiga** [comment]
The gems tests didn't run on 1.8.7 or some such :P You can always check the commits :)

**Comment by Danicela** [comment]
How do you use the new order attribute ? (I mean, can you give me a syntax exemple, I'm beginner in Ruby)

**Comment by deiga** [comment]
Theres no special syntax there, it just keeps the order of elements. As a Hash in ruby 1.8.7 sorts elements automatically, which broke the order I needed :)

**Comment by Danicela** [comment]
Do you mean that for Ruby >1.8.7, nokogiri-happymapper already does the correct ordering ?

**Comment by deiga** [comment]
AFAIK Hashes in ruby 1.9 keep the order of elements according to the order they were added, so yeah, in ruby >= 1.9 the ordering should work intrinsicly

**Comment by mvz** [comment]
Closing this since according to https://github.com/mvz/happymapper/pull/55#issuecomment-130409945 this works in all currently supported Ruby versions.

**Pull request closed without merging**
